name: continual_care_alpha
description: Giving back through caregiving
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.2
  omni_datetime_picker: ^0.1.2
  equatable: ^2.0.3
  firestore_jobs_api:
    path: packages/firestore_jobs_api
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  intl: ^0.17.0
  jobs_api:
    path: packages/jobs_api
  jobs_repository:
    path: packages/jobs_repository
  transparent_image: ^2.0.0
  firebase_core: ^1.21.1
  rive: ^0.8.4


dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  flutter_launcher_icons: "^0.11.0"
  icons_launcher: ^2.0.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

icons_launcher:
  image_path: 'assets/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true