// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl21SjVNazLXRY4MnBWN_wRIjvXD6Gr1s',
    appId: '1:243155743060:web:4b5b7d17dd216310b858c1',
    messagingSenderId: '243155743060',
    projectId: 'continual-care',
    authDomain: 'continual-care.firebaseapp.com',
    storageBucket: 'continual-care.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrErPoDlvUlNDLGdroxZQbWXufeC5eAbw',
    appId: '1:243155743060:android:d5893a7a1f5d5a3bb858c1',
    messagingSenderId: '243155743060',
    projectId: 'continual-care',
    storageBucket: 'continual-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfWIdOEfsUxonGyoFFVS1AHOPv3EXuGUc',
    appId: '1:243155743060:ios:c88f067d6784907db858c1',
    messagingSenderId: '243155743060',
    projectId: 'continual-care',
    storageBucket: 'continual-care.appspot.com',
    iosClientId: '243155743060-dj41jq96t0ia8tee1t9l2dbsuerivt23.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.continual-care-alpha',
  );
}
